export type TranslationKey = 
  | 'nav.home' | 'nav.world' | 'nav.favorites' | 'nav.myPlaylists' | 'nav.settings' | 'nav.about'
  | 'home.discover' | 'home.liveTv' | 'home.subtitle' | 'home.showingChannels' | 'home.search' | 'home.allChannels' | 'home.noChannels' | 'home.tryAdjusting'
  | 'world.title' | 'world.subtitle'
  | 'fav.title' | 'fav.subtitle' | 'fav.noFavs' | 'fav.clickHeart'
  | 'playlists.title' | 'playlists.subtitle' | 'playlists.dragDrop' | 'playlists.select' | 'playlists.noPlaylists' | 'playlists.uploadDesc' | 'playlists.channels'
  | 'settings.title' | 'settings.subtitle' | 'settings.theme' | 'settings.themeDesc' | 'settings.engine' | 'settings.engineDesc' | 'settings.autoplay' | 'settings.autoplayDesc' | 'settings.language' | 'settings.languageDesc'
  | 'settings.theme.dark' | 'settings.theme.light' | 'settings.theme.oled'
  | 'about.title' | 'about.subtitle' | 'about.version' | 'about.engine' | 'about.changelogs' | 'about.tryMobile' | 'about.free' | 'about.noAds' | 'about.openSource' | 'about.security' | 'about.securityDesc' | 'about.github' | 'about.website'
  | 'terms.title' | 'terms.subtitle' | 'terms.desc1' | 'terms.desc2' | 'terms.desc3' | 'terms.accept'
  | 'player.streamError' | 'player.streamErrorDesc' | 'player.dismiss';

type Dictionary = Record<TranslationKey, string>;

export const dictionaries: Record<string, Dictionary> = {
  en: {
    'nav.home': 'Home', 'nav.world': 'World', 'nav.favorites': 'Favorites', 'nav.myPlaylists': 'My Playlists', 'nav.settings': 'Settings', 'nav.about': 'About',
    'home.discover': 'Discover', 'home.liveTv': 'Live TV', 'home.subtitle': 'Stream your favorite channels with unparalleled speed and a stunning, distraction-free interface.', 'home.showingChannels': 'Showing {0} channels', 'home.search': 'Search channels, movies, sports...', 'home.allChannels': 'All Channels', 'home.noChannels': 'No channels found', 'home.tryAdjusting': 'Try adjusting your search or category filter.',
    'world.title': 'World Channels', 'world.subtitle': 'Explore 18,000+ international channels from around the globe.',
    'fav.title': 'Your Favorites', 'fav.subtitle': 'Curated collection of your most-watched channels.', 'fav.noFavs': 'No favorites yet', 'fav.clickHeart': 'Click the heart icon on any channel to save it here.',
    'playlists.title': 'My Playlists', 'playlists.subtitle': 'Upload and manage your own custom M3U playlists. Playlists are stored locally in your browser offline cache.', 'playlists.dragDrop': 'Drag & Drop your .m3u file here', 'playlists.select': 'Select Playlist', 'playlists.noPlaylists': 'No custom playlists yet', 'playlists.uploadDesc': 'Upload an M3U file above and it will securely appear here as a folder.', 'playlists.channels': 'Channels',
    'settings.title': 'Settings', 'settings.subtitle': 'Customize your viewing experience and application preferences.', 'settings.theme': 'App Theme', 'settings.themeDesc': 'Choose your preferred visual aesthetic.', 'settings.engine': 'Video Engine', 'settings.engineDesc': 'Select the core playback engine. If a stream fails, try switching engines.', 'settings.autoplay': 'Auto-play Channels', 'settings.autoplayDesc': 'Automatically start playing video when a channel is selected.', 'settings.language': 'Language', 'settings.languageDesc': 'Select your preferred display language.',
    'settings.theme.dark': 'Dark', 'settings.theme.light': 'Light', 'settings.theme.oled': 'OLED',
    'about.title': 'About', 'about.subtitle': 'FreeIPTV Web is a modern, lag-less live TV streaming application designed from the ground up for the ultimate viewing experience.', 'about.version': 'Version', 'about.engine': 'Engine', 'about.changelogs': 'Changelogs', 'about.tryMobile': 'Try Our Mobile App!', 'about.free': 'Free Forever', 'about.noAds': 'No Ads', 'about.openSource': 'Open Source', 'about.security': 'Security Notice:', 'about.securityDesc': 'Please only download the app from our official GitHub Releases to avoid malicious or unofficial APKs.', 'about.github': 'GitHub Releases', 'about.website': 'Official Website',
    'terms.title': 'Legal Disclaimer', 'terms.subtitle': 'Please read carefully before using FreeIPTV Web', 'terms.desc1': 'No Content Hosting: FreeIPTV Web is strictly a media player interface. We do not host, broadcast, or distribute any video streams, movies, or copyrighted content on our servers.', 'terms.desc2': 'User Responsibility: Any M3U playlists or stream links loaded into this application are the sole responsibility of the user. We are not responsible for the contents of user-uploaded playlists.', 'terms.desc3': 'Local Data: We do not collect or transmit your personal data or playlist contents to remote servers. All data is stored locally in your browser offline cache.', 'terms.accept': 'I Understand & Accept',
    'player.streamError': 'Stream Error', 'player.streamErrorDesc': 'This channel failed to load or is geo-blocked. Try using a free encrypted VPN to bypass ISP blocks.', 'player.dismiss': 'Dismiss'
  },
  bn: {
    'nav.home': 'হোম', 'nav.world': 'বিশ্ব', 'nav.favorites': 'প্রিয় চ্যানেল', 'nav.myPlaylists': 'আমার প্লেলিস্ট', 'nav.settings': 'সেটিংস', 'nav.about': 'আমাদের সম্পর্কে',
    'home.discover': 'উপভোগ করুন', 'home.liveTv': 'লাইভ টিভি', 'home.subtitle': 'অবিশ্বাস্য গতি এবং দারুণ, বাধাহীন ইন্টারফেসে আপনার পছন্দের চ্যানেলগুলো স্ট্রিম করুন।', 'home.showingChannels': '{0} টি চ্যানেল দেখানো হচ্ছে', 'home.search': 'চ্যানেল, মুভি বা খেলাধুলা খুঁজুন...', 'home.allChannels': 'সব চ্যানেল', 'home.noChannels': 'কোনো চ্যানেল পাওয়া যায়নি', 'home.tryAdjusting': 'আপনার ফিল্টার বা সার্চ কিওয়ার্ড পরিবর্তন করে দেখতে পারেন।',
    'world.title': 'আন্তর্জাতিক চ্যানেল', 'world.subtitle': 'বিশ্বজুড়ে ছড়িয়ে থাকা ১৮,০০০-এর বেশি চ্যানেল এক্সপ্লোর করুন।',
    'fav.title': 'আপনার প্রিয় চ্যানেল', 'fav.subtitle': 'আপনার সবচেয়ে বেশি দেখা চ্যানেলগুলোর তালিকা।', 'fav.noFavs': 'কোনো প্রিয় চ্যানেল নেই', 'fav.clickHeart': 'যেকোনো চ্যানেলের হার্ট আইকনে ক্লিক করে এখানে সেভ করে রাখতে পারেন।',
    'playlists.title': 'আমার প্লেলিস্ট', 'playlists.subtitle': 'আপনার নিজস্ব M3U প্লেলিস্ট আপলোড করে পরিচালনা করুন। প্লেলিস্টগুলো অফলাইনে আপনার ব্রাউজারেই সেভ থাকে।', 'playlists.dragDrop': 'আপনার .m3u ফাইলটি এখানে টেনে আনুন', 'playlists.select': 'প্লেলিস্ট সিলেক্ট করুন', 'playlists.noPlaylists': 'কোনো কাস্টম প্লেলিস্ট নেই', 'playlists.uploadDesc': 'উপরে একটি M3U ফাইল আপলোড করলে সেটি এখানে ফোল্ডার হিসেবে সেভ হবে।', 'playlists.channels': 'চ্যানেল',
    'settings.title': 'সেটিংস', 'settings.subtitle': 'আপনার পছন্দ অনুযায়ী অ্যাপ কাস্টমাইজ করুন।', 'settings.theme': 'অ্যাপ থিম', 'settings.themeDesc': 'আপনার পছন্দের ভিজ্যুয়াল থিম বেছে নিন।', 'settings.engine': 'ভিডিও ইঞ্জিন', 'settings.engineDesc': 'মূল প্লেব্যাক ইঞ্জিন নির্বাচন করুন। কোনো স্ট্রিম না চললে অন্য ইঞ্জিন ট্রাই করে দেখতে পারেন।', 'settings.autoplay': 'অটো-প্লে', 'settings.autoplayDesc': 'কোনো চ্যানেল সিলেক্ট করার সাথে সাথেই স্বয়ংক্রিয়ভাবে ভিডিও প্লে হবে।', 'settings.language': 'ভাষা', 'settings.languageDesc': 'আপনার সুবিধামতো ভাষা নির্বাচন করুন।',
    'settings.theme.dark': 'ডার্ক', 'settings.theme.light': 'লাইট', 'settings.theme.oled': 'পিওর ওএলইডি',
    'about.title': 'আমাদের সম্পর্কে', 'about.subtitle': 'ফ্রিআইপিটিভি ওয়েব মূলত একটি আধুনিক, ল্যাগ-ফ্রি লাইভ টিভি স্ট্রিমিং অ্যাপ, যা দারুণ অভিজ্ঞতা দেওয়ার জন্য তৈরি।', 'about.version': 'ভার্সন', 'about.engine': 'ইঞ্জিন', 'about.changelogs': 'আপডেট লগ', 'about.tryMobile': 'আমাদের মোবাইল অ্যাপটি ট্রাই করে দেখুন!', 'about.free': 'সম্পূর্ণ ফ্রি', 'about.noAds': 'বিজ্ঞাপন মুক্ত', 'about.openSource': 'ওপেন সোর্স', 'about.security': 'সতর্কতা:', 'about.securityDesc': 'ক্ষতিকর অ্যাপ থেকে বাঁচতে শুধুমাত্র আমাদের অফিসিয়াল গিটহাব রিলিজ থেকে অ্যাপটি ডাউনলোড করুন।', 'about.github': 'গিটহাব রিলিজ', 'about.website': 'অফিসিয়াল ওয়েবসাইট',
    'terms.title': 'আইনি সতর্কবার্তা', 'terms.subtitle': 'অ্যাপটি ব্যবহারের আগে দয়া করে শর্তাবলি পড়ে নিন', 'terms.desc1': 'কোনো কনটেন্ট হোস্টিং নেই: ফ্রিআইপিটিভি ওয়েব মূলত একটি মিডিয়া প্লেয়ার। আমরা আমাদের সার্ভারে কোনো ভিডিও, মুভি বা কপিরাইটযুক্ত কনটেন্ট হোস্ট বা সম্প্রচার করি না।', 'terms.desc2': 'ব্যবহারকারীর দায়বদ্ধতা: এই অ্যাপে আপলোড করা যেকোনো M3U প্লেলিস্ট বা লিংকের জন্য সম্পূর্ণ দায়ভার ব্যবহারকারীর। আপলোড করা কোনো প্লেলিস্টের কনটেন্টের জন্য আমরা দায়ী নই।', 'terms.desc3': 'লোকাল ডেটা: আমরা আপনার কোনো ব্যক্তিগত ডেটা বা প্লেলিস্ট সংগ্রহ করে রিমোট সার্ভারে পাঠাই না। সমস্ত ডেটা আপনার ব্রাউজারেই অফলাইনে সেভ থাকে।', 'terms.accept': 'আমি বুঝতে পেরেছি এবং সম্মত',
    'player.streamError': 'স্ট্রিমিং সমস্যা', 'player.streamErrorDesc': 'চ্যানেলটি লোড হচ্ছে না বা আপনার এলাকায় ব্লক করা আছে। ব্লক বাইপাস করতে কোনো ফ্রি ভিপিএন (VPN) ব্যবহার করে দেখতে পারেন।', 'player.dismiss': 'বন্ধ করুন'
  },
  es: {
    'nav.home': 'Inicio', 'nav.world': 'Mundial', 'nav.favorites': 'Favoritos', 'nav.myPlaylists': 'Mis Listas', 'nav.settings': 'Ajustes', 'nav.about': 'Acerca de',
    'home.discover': 'Disfruta de la', 'home.liveTv': 'TV en Vivo', 'home.subtitle': 'Transmite tus canales favoritos con una velocidad increíble y una interfaz limpia, sin distracciones.', 'home.showingChannels': 'Mostrando {0} canales', 'home.search': 'Buscar canales, películas, deportes...', 'home.allChannels': 'Todos los canales', 'home.noChannels': 'No se encontraron canales', 'home.tryAdjusting': 'Intenta cambiar tus filtros o términos de búsqueda.',
    'world.title': 'Canales Globales', 'world.subtitle': 'Explora más de 18,000 canales internacionales de todo el mundo.',
    'fav.title': 'Tus Favoritos', 'fav.subtitle': 'La colección de tus canales más vistos y preferidos.', 'fav.noFavs': 'Aún no hay favoritos', 'fav.clickHeart': 'Haz clic en el icono del corazón en cualquier canal para guardarlo aquí.',
    'playlists.title': 'Mis Listas', 'playlists.subtitle': 'Sube y organiza tus propias listas M3U personalizadas. Todo se guarda localmente en tu navegador.', 'playlists.dragDrop': 'Arrastra tu archivo .m3u aquí', 'playlists.select': 'Seleccionar archivo', 'playlists.noPlaylists': 'No tienes listas personalizadas', 'playlists.uploadDesc': 'Sube un archivo M3U y aparecerá aquí almacenado de forma segura.', 'playlists.channels': 'Canales',
    'settings.title': 'Ajustes', 'settings.subtitle': 'Personaliza tu experiencia y las preferencias de la aplicación.', 'settings.theme': 'Tema visual', 'settings.themeDesc': 'Elige el estilo visual que más te guste.', 'settings.engine': 'Motor de video', 'settings.engineDesc': 'Selecciona el motor de reproducción. Si un canal no funciona, intenta cambiarlo.', 'settings.autoplay': 'Reproducción automática', 'settings.autoplayDesc': 'Reproducir el video automáticamente al seleccionar un canal.', 'settings.language': 'Idioma', 'settings.languageDesc': 'Elige el idioma de la aplicación.',
    'settings.theme.dark': 'Oscuro', 'settings.theme.light': 'Claro', 'settings.theme.oled': 'OLED Puro',
    'about.title': 'Acerca de', 'about.subtitle': 'FreeIPTV Web es una aplicación moderna de transmisión sin demoras, diseñada para la mejor experiencia.', 'about.version': 'Versión', 'about.engine': 'Motor', 'about.changelogs': 'Novedades', 'about.tryMobile': '¡Prueba nuestra app móvil!', 'about.free': '100% Gratis', 'about.noAds': 'Sin Anuncios', 'about.openSource': 'Código Abierto', 'about.security': 'Aviso de seguridad:', 'about.securityDesc': 'Por favor, descarga la app solo desde nuestros lanzamientos oficiales en GitHub para evitar archivos maliciosos.', 'about.github': 'Lanzamientos en GitHub', 'about.website': 'Sitio Web Oficial',
    'terms.title': 'Aviso Legal', 'terms.subtitle': 'Lee atentamente antes de usar FreeIPTV Web', 'terms.desc1': 'Sin alojamiento de contenido: FreeIPTV Web es únicamente un reproductor multimedia. No alojamos, emitimos ni distribuimos ningún tipo de contenido protegido por derechos de autor.', 'terms.desc2': 'Responsabilidad del usuario: Cualquier lista M3U o enlace cargado en esta aplicación es responsabilidad exclusiva del usuario. No nos hacemos responsables del contenido subido.', 'terms.desc3': 'Privacidad: No recopilamos ni enviamos tus datos personales. Todo se almacena localmente en la memoria caché de tu navegador.', 'terms.accept': 'Entiendo y Acepto',
    'player.streamError': 'Error de conexión', 'player.streamErrorDesc': 'No se pudo cargar este canal o está bloqueado en tu región. Prueba usando una VPN gratuita para evitar bloqueos del proveedor.', 'player.dismiss': 'Cerrar'
  },
  ru: {
    'nav.home': 'Главная', 'nav.world': 'Мир', 'nav.favorites': 'Избранное', 'nav.myPlaylists': 'Мои плейлисты', 'nav.settings': 'Настройки', 'nav.about': 'О нас',
    'home.discover': 'Смотрите', 'home.liveTv': 'Прямой эфир', 'home.subtitle': 'Наслаждайтесь любимыми каналами с невероятной скоростью в удобном интерфейсе без отвлекающих элементов.', 'home.showingChannels': 'Показано каналов: {0}', 'home.search': 'Искать каналы, фильмы, спорт...', 'home.allChannels': 'Все каналы', 'home.noChannels': 'Ничего не найдено', 'home.tryAdjusting': 'Попробуйте изменить поисковый запрос или фильтры.',
    'world.title': 'Каналы со всего мира', 'world.subtitle': 'Исследуйте более 18 000 международных каналов.',
    'fav.title': 'Ваше избранное', 'fav.subtitle': 'Коллекция каналов, которые вы смотрите чаще всего.', 'fav.noFavs': 'Пока нет избранного', 'fav.clickHeart': 'Нажмите на значок сердечка на любом канале, чтобы сохранить его здесь.',
    'playlists.title': 'Мои плейлисты', 'playlists.subtitle': 'Загружайте свои собственные M3U-плейлисты. Данные надежно сохраняются прямо в вашем браузере.', 'playlists.dragDrop': 'Перетащите ваш файл .m3u сюда', 'playlists.select': 'Выбрать файл', 'playlists.noPlaylists': 'Нет добавленных плейлистов', 'playlists.uploadDesc': 'Загрузите файл M3U, и он появится здесь в виде папки.', 'playlists.channels': 'Каналы',
    'settings.title': 'Настройки', 'settings.subtitle': 'Настройте просмотр и интерфейс приложения под себя.', 'settings.theme': 'Внешний вид', 'settings.themeDesc': 'Выберите предпочитаемый визуальный стиль оформления.', 'settings.engine': 'Видеоплеер', 'settings.engineDesc': 'Выберите основной движок воспроизведения. Если трансляция зависает, попробуйте сменить его.', 'settings.autoplay': 'Автовоспроизведение', 'settings.autoplayDesc': 'Автоматически запускать трансляцию при выборе канала.', 'settings.language': 'Язык', 'settings.languageDesc': 'Выберите язык интерфейса.',
    'settings.theme.dark': 'Темная', 'settings.theme.light': 'Светлая', 'settings.theme.oled': 'OLED',
    'about.title': 'О приложении', 'about.subtitle': 'FreeIPTV Web — это современный онлайн-плеер без задержек для максимально комфортного просмотра ТВ.', 'about.version': 'Версия', 'about.engine': 'Движок', 'about.changelogs': 'Что нового', 'about.tryMobile': 'Попробуйте наше мобильное приложение!', 'about.free': 'Абсолютно бесплатно', 'about.noAds': 'Без рекламы', 'about.openSource': 'Открытый код', 'about.security': 'Безопасность:', 'about.securityDesc': 'Скачивайте приложение только с официальной страницы GitHub во избежание вирусов.', 'about.github': 'Скачать с GitHub', 'about.website': 'Официальный сайт',
    'terms.title': 'Отказ от ответственности', 'terms.subtitle': 'Пожалуйста, внимательно ознакомьтесь перед использованием', 'terms.desc1': 'Никакого хостинга: FreeIPTV Web работает исключительно как медиаплеер. Мы не размещаем и не распространяем видеопотоки или защищенный авторским правом контент.', 'terms.desc2': 'Ответственность пользователя: Ответственность за любые M3U-плейлисты несет только пользователь. Мы не проверяем содержимое ваших плейлистов.', 'terms.desc3': 'Локальные данные: Мы не собираем ваши личные данные. Все настройки и плейлисты хранятся только в кэше вашего браузера.', 'terms.accept': 'Я понимаю и соглашаюсь',
    'player.streamError': 'Ошибка воспроизведения', 'player.streamErrorDesc': 'Не удалось загрузить канал. Возможно, он заблокирован в вашем регионе. Попробуйте использовать бесплатный VPN.', 'player.dismiss': 'Закрыть'
  },
  ar: {
    'nav.home': 'الرئيسية', 'nav.world': 'حول العالم', 'nav.favorites': 'المفضلة', 'nav.myPlaylists': 'قوائم التشغيل', 'nav.settings': 'الإعدادات', 'nav.about': 'حول التطبيق',
    'home.discover': 'استمتع بمشاهدة', 'home.liveTv': 'البث المباشر', 'home.subtitle': 'شاهد قنواتك المفضلة بسرعة فائقة وواجهة أنيقة خالية من أي مشتتات.', 'home.showingChannels': 'عرض {0} قنوات', 'home.search': 'ابحث عن القنوات، الأفلام، الرياضة...', 'home.allChannels': 'كل القنوات', 'home.noChannels': 'لم يتم العثور على أي قنوات', 'home.tryAdjusting': 'حاول تعديل كلمات البحث أو الفلتر.',
    'world.title': 'قنوات عالمية', 'world.subtitle': 'اكتشف أكثر من 18,000 قناة دولية من جميع أنحاء العالم.',
    'fav.title': 'قنواتك المفضلة', 'fav.subtitle': 'مجموعتك المختارة لأكثر القنوات التي تحب مشاهدتها.', 'fav.noFavs': 'لا توجد قنوات مفضلة بعد', 'fav.clickHeart': 'اضغط على أيقونة القلب الموجودة على أي قناة لحفظها هنا.',
    'playlists.title': 'قوائم التشغيل الخاصة بي', 'playlists.subtitle': 'قم برفع وإدارة قوائم M3U الخاصة بك. يتم حفظها بأمان في متصفحك محلياً.', 'playlists.dragDrop': 'قم بسحب وإفلات ملف .m3u هنا', 'playlists.select': 'اختر ملف', 'playlists.noPlaylists': 'لا توجد قوائم مخصصة', 'playlists.uploadDesc': 'ارفع ملف M3U من الأعلى وسيظهر هنا بشكل آمن كملف.', 'playlists.channels': 'قنوات',
    'settings.title': 'الإعدادات', 'settings.subtitle': 'قم بتخصيص تجربة المشاهدة والتطبيق حسب رغبتك.', 'settings.theme': 'مظهر التطبيق', 'settings.themeDesc': 'اختر التصميم الذي يريح عينيك.', 'settings.engine': 'مشغل الفيديو', 'settings.engineDesc': 'اختر مشغل الفيديو الأساسي. في حال تعطل البث، جرب التبديل لمحرك آخر.', 'settings.autoplay': 'التشغيل التلقائي', 'settings.autoplayDesc': 'تشغيل الفيديو تلقائياً بمجرد اختيار القناة.', 'settings.language': 'اللغة', 'settings.languageDesc': 'اختر لغة العرض المفضلة.',
    'settings.theme.dark': 'داكن', 'settings.theme.light': 'فاتح', 'settings.theme.oled': 'OLED نقي',
    'about.title': 'حول التطبيق', 'about.subtitle': 'تطبيق FreeIPTV Web هو مشغل حديث وسريع للبث المباشر، مصمم لتقديم أفضل تجربة مشاهدة.', 'about.version': 'الإصدار', 'about.engine': 'المشغل', 'about.changelogs': 'آخر التحديثات', 'about.tryMobile': 'جرب تطبيق الموبايل الخاص بنا!', 'about.free': 'مجاني للأبد', 'about.noAds': 'بدون إعلانات', 'about.openSource': 'مفتوح المصدر', 'about.security': 'تنبيه أمني:', 'about.securityDesc': 'يرجى تحميل التطبيق حصرياً من صفحتنا الرسمية على GitHub لتجنب الملفات الضارة.', 'about.github': 'إصدارات GitHub', 'about.website': 'الموقع الرسمي',
    'terms.title': 'إخلاء مسؤولية', 'terms.subtitle': 'يرجى القراءة بعناية قبل الاستخدام', 'terms.desc1': 'لا نستضيف أي محتوى: تطبيق FreeIPTV Web هو مجرد مشغل وسائط. نحن لا نستضيف أو نبث أو نوزع أي قنوات أو محتوى محمي بحقوق الطبع والنشر.', 'terms.desc2': 'مسؤولية المستخدم: يتحمل المستخدم وحده المسؤولية الكاملة عن أي روابط أو قوائم M3U يتم رفعها هنا.', 'terms.desc3': 'خصوصية البيانات: نحن لا نجمع بياناتك ولا نرسلها إلى أي خوادم خارجية. يتم تخزين كل شيء على متصفحك محلياً فقط.', 'terms.accept': 'فهمت وأوافق',
    'player.streamError': 'خطأ في البث', 'player.streamErrorDesc': 'تعذر تحميل القناة، قد تكون محظورة في منطقتك. حاول استخدام تطبيق VPN مجاني لتجاوز الحظر.', 'player.dismiss': 'إغلاق'
  },
  hi: {
    'nav.home': 'होम', 'nav.world': 'दुनिया', 'nav.favorites': 'पसंदीदा', 'nav.myPlaylists': 'मेरी प्लेलिस्ट', 'nav.settings': 'सेटिंग्स', 'nav.about': 'हमारे बारे में',
    'home.discover': 'आनंद लें', 'home.liveTv': 'लाइव टीवी का', 'home.subtitle': 'बेजोड़ स्पीड और बिना किसी रुकावट वाले शानदार इंटरफ़ेस पर अपने पसंदीदा चैनल स्ट्रीम करें।', 'home.showingChannels': '{0} चैनल दिखा रहा है', 'home.search': 'चैनल, फिल्में या खेल खोजें...', 'home.allChannels': 'सभी चैनल', 'home.noChannels': 'कोई चैनल नहीं मिला', 'home.tryAdjusting': 'अपनी खोज या फ़िल्टर बदलकर प्रयास करें।',
    'world.title': 'अंतर्राष्ट्रीय चैनल', 'world.subtitle': 'दुनिया भर के 18,000+ से अधिक अंतर्राष्ट्रीय चैनलों का मज़ा लें।',
    'fav.title': 'आपके पसंदीदा', 'fav.subtitle': 'आपके सबसे ज्यादा देखे गए और पसंदीदा चैनलों का संग्रह।', 'fav.noFavs': 'अभी तक कोई पसंदीदा नहीं', 'fav.clickHeart': 'किसी भी चैनल को यहाँ सेव करने के लिए उसके हार्ट आइकन पर क्लिक करें।',
    'playlists.title': 'मेरी प्लेलिस्ट', 'playlists.subtitle': 'अपनी खुद की कस्टम M3U प्लेलिस्ट अपलोड करें। सब कुछ आपके ब्राउज़र में सुरक्षित रहता है।', 'playlists.dragDrop': 'अपनी .m3u फ़ाइल यहाँ छोड़ें', 'playlists.select': 'फ़ाइल चुनें', 'playlists.noPlaylists': 'कोई कस्टम प्लेलिस्ट नहीं', 'playlists.uploadDesc': 'ऊपर एक M3U फ़ाइल अपलोड करें और वह यहाँ फ़ोल्डर के रूप में दिखाई देगी।', 'playlists.channels': 'चैनल',
    'settings.title': 'सेटिंग्स', 'settings.subtitle': 'अपने देखने के अनुभव और ऐप प्राथमिकताओं को कस्टमाइज़ करें।', 'settings.theme': 'ऐप थीम', 'settings.themeDesc': 'अपना पसंदीदा विज़ुअल स्टाइल चुनें।', 'settings.engine': 'वीडियो इंजन', 'settings.engineDesc': 'मुख्य वीडियो प्लेयर चुनें। यदि कोई स्ट्रीम काम नहीं कर रही है, तो इंजन बदलकर देखें।', 'settings.autoplay': 'ऑटो-प्ले', 'settings.autoplayDesc': 'चैनल पर क्लिक करते ही स्वचालित रूप से वीडियो चलाना शुरू करें।', 'settings.language': 'भाषा', 'settings.languageDesc': 'अपनी पसंदीदा भाषा चुनें।',
    'settings.theme.dark': 'डार्क', 'settings.theme.light': 'लाइट', 'settings.theme.oled': 'प्योर OLED',
    'about.title': 'हमारे बारे में', 'about.subtitle': 'FreeIPTV Web एक आधुनिक और तेज़ लाइव टीवी ऐप है, जो आपको बेहतरीन अनुभव देने के लिए डिज़ाइन किया गया है।', 'about.version': 'वर्ज़न', 'about.engine': 'इंजन', 'about.changelogs': 'नए अपडेट्स', 'about.tryMobile': 'हमारा मोबाइल ऐप आज़माएं!', 'about.free': 'पूरी तरह मुफ़्त', 'about.noAds': 'बिना विज्ञापन', 'about.openSource': 'ओपन सोर्स', 'about.security': 'सुरक्षा अलर्ट:', 'about.securityDesc': 'दुर्भावनापूर्ण ऐप्स से बचने के लिए कृपया ऐप को केवल हमारे आधिकारिक GitHub पेज से ही डाउनलोड करें।', 'about.github': 'GitHub रिलीज़', 'about.website': 'आधिकारिक वेबसाइट',
    'terms.title': 'कानूनी अस्वीकरण', 'terms.subtitle': 'उपयोग करने से पहले कृपया इसे ध्यान से पढ़ें', 'terms.desc1': 'कोई कंटेंट होस्टिंग नहीं: यह ऐप पूरी तरह से सिर्फ एक मीडिया प्लेयर है। हम अपने सर्वर पर कोई वीडियो या कॉपीराइट कंटेंट होस्ट नहीं करते हैं।', 'terms.desc2': 'उपयोगकर्ता की जिम्मेदारी: ऐप में जोड़ी गई किसी भी M3U प्लेलिस्ट या लिंक के लिए केवल उपयोगकर्ता जिम्मेदार है।', 'terms.desc3': 'लोकल डेटा: हम आपका व्यक्तिगत डेटा एकत्र नहीं करते हैं। सभी डेटा आपके डिवाइस पर ऑफ़लाइन सुरक्षित रूप से सहेजा जाता है।', 'terms.accept': 'मैं सहमत हूँ',
    'player.streamError': 'स्ट्रीमिंग त्रुटि', 'player.streamErrorDesc': 'यह चैनल लोड नहीं हो रहा है या आपके क्षेत्र में ब्लॉक है। किसी मुफ़्त VPN का उपयोग करके प्रयास करें।', 'player.dismiss': 'बंद करें'
  },
  ja: {
    'nav.home': 'ホーム', 'nav.world': '世界', 'nav.favorites': 'お気に入り', 'nav.myPlaylists': 'マイプレイリスト', 'nav.settings': '設定', 'nav.about': 'アプリについて',
    'home.discover': '快適な', 'home.liveTv': 'ライブTV体験', 'home.subtitle': '圧倒的なスピードと美しいインターフェースで、お気に入りのチャンネルをノーストレスで視聴しましょう。', 'home.showingChannels': '{0} チャンネルを表示中', 'home.search': 'チャンネル、映画、スポーツを検索...', 'home.allChannels': 'すべてのチャンネル', 'home.noChannels': 'チャンネルが見つかりません', 'home.tryAdjusting': '検索ワードやカテゴリーを変更してみてください。',
    'world.title': '世界のチャンネル', 'world.subtitle': '世界中の18,000以上の国際チャンネルを心ゆくまでお楽しみください。',
    'fav.title': 'お気に入り', 'fav.subtitle': 'よく見るお気に入りチャンネルのコレクションです。', 'fav.noFavs': 'お気に入りはまだありません', 'fav.clickHeart': '各チャンネルのハートアイコンをクリックして、ここに保存しましょう。',
    'playlists.title': 'マイプレイリスト', 'playlists.subtitle': '独自のM3Uプレイリストをアップロードして管理できます。データはブラウザ内に安全に保存されます。', 'playlists.dragDrop': 'ここに .m3u ファイルをドロップ', 'playlists.select': 'ファイルを選択', 'playlists.noPlaylists': 'カスタムプレイリストがありません', 'playlists.uploadDesc': 'M3Uファイルをアップロードすると、ここにフォルダとして表示されます。', 'playlists.channels': 'チャンネル',
    'settings.title': '設定', 'settings.subtitle': 'アプリの動作や表示をお好みにカスタマイズできます。', 'settings.theme': 'テーマ', 'settings.themeDesc': '好みのデザインテーマを選択してください。', 'settings.engine': 'ビデオエンジン', 'settings.engineDesc': '再生エンジンを選択します。再生できない場合はエンジンを切り替えてみてください。', 'settings.autoplay': '自動再生', 'settings.autoplayDesc': 'チャンネルを選択するとすぐに動画の再生を開始します。', 'settings.language': '言語', 'settings.languageDesc': '表示言語を選択してください。',
    'settings.theme.dark': 'ダーク', 'settings.theme.light': 'ライト', 'settings.theme.oled': 'ピュアOLED',
    'about.title': 'アプリについて', 'about.subtitle': 'FreeIPTV Web は、究極の視聴体験のためにゼロから設計された、最新のラグなしライブTVアプリです。', 'about.version': 'バージョン', 'about.engine': 'エンジン', 'about.changelogs': 'アップデート履歴', 'about.tryMobile': 'モバイルアプリもお試しください！', 'about.free': '完全無料', 'about.noAds': '広告なし', 'about.openSource': 'オープンソース', 'about.security': 'セキュリティに関する注意:', 'about.securityDesc': '悪意のある偽アプリを避けるため、公式のGitHubからのみダウンロードしてください。', 'about.github': 'GitHub リリース', 'about.website': '公式サイト',
    'terms.title': '免責事項', 'terms.subtitle': 'ご利用前に必ずお読みください', 'terms.desc1': 'コンテンツのホスティングについて: 当アプリは単なるメディアプレーヤーです。著作権で保護されたコンテンツや動画を配信・ホストすることはありません。', 'terms.desc2': 'ユーザーの責任: ユーザーが読み込んだM3Uプレイリストの内容については、すべてユーザー自身が責任を負うものとします。', 'terms.desc3': 'データのプライバシー: 当アプリが個人データを収集したりサーバーに送信することはありません。すべてのデータはお使いの端末に保存されます。', 'terms.accept': '同意して利用を開始する',
    'player.streamError': '再生エラー', 'player.streamErrorDesc': 'チャンネルの読み込みに失敗したか、地域制限がかかっています。無料のVPNを使用すると解決する場合があります。', 'player.dismiss': '閉じる'
  },
  zh: {
    'nav.home': '首页', 'nav.world': '全球', 'nav.favorites': '我的收藏', 'nav.myPlaylists': '我的歌单', 'nav.settings': '设置', 'nav.about': '关于我们',
    'home.discover': '畅享', 'home.liveTv': '直播电视', 'home.subtitle': '以无与伦比的速度和纯净清爽的界面，流畅观看您喜爱的频道。', 'home.showingChannels': '当前显示 {0} 个频道', 'home.search': '搜索频道、电影或体育赛事...', 'home.allChannels': '全部频道', 'home.noChannels': '未找到任何频道', 'home.tryAdjusting': '请尝试修改搜索词或类别过滤器。',
    'world.title': '全球频道', 'world.subtitle': '探索来自世界各地超过 18,000 个国际频道。',
    'fav.title': '我的收藏', 'fav.subtitle': '您最常观看的精选频道列表。', 'fav.noFavs': '暂无收藏', 'fav.clickHeart': '点击频道上的心形图标即可将其保存到这里。',
    'playlists.title': '我的播放列表', 'playlists.subtitle': '上传并管理您自己的 M3U 播放列表。您的数据将安全地保存在浏览器本地。', 'playlists.dragDrop': '将 .m3u 文件拖放到此处', 'playlists.select': '选择文件', 'playlists.noPlaylists': '暂无自定义列表', 'playlists.uploadDesc': '上传 M3U 文件后，它将作为文件夹安全地显示在这里。', 'playlists.channels': '频道',
    'settings.title': '设置', 'settings.subtitle': '个性化定制您的观看体验和应用偏好。', 'settings.theme': '应用主题', 'settings.themeDesc': '选择您喜欢的视觉外观。', 'settings.engine': '视频引擎', 'settings.engineDesc': '选择核心播放器。如果频道无法播放，请尝试切换引擎。', 'settings.autoplay': '自动播放', 'settings.autoplayDesc': '点击频道后自动开始播放视频。', 'settings.language': '语言', 'settings.languageDesc': '选择您习惯的显示语言。',
    'settings.theme.dark': '深色', 'settings.theme.light': '浅色', 'settings.theme.oled': '纯黑 OLED',
    'about.title': '关于我们', 'about.subtitle': 'FreeIPTV Web 是一款现代、无延迟的直播应用，专为极致观看体验而打造。', 'about.version': '版本', 'about.engine': '引擎', 'about.changelogs': '更新日志', 'about.tryMobile': '欢迎体验我们的手机App！', 'about.free': '永久免费', 'about.noAds': '无广告', 'about.openSource': '开源项目', 'about.security': '安全提示:', 'about.securityDesc': '为了您的设备安全，请仅从我们的官方 GitHub 下载应用，谨防恶意软件。', 'about.github': 'GitHub 发布页', 'about.website': '官方网站',
    'terms.title': '免责声明', 'terms.subtitle': '使用前请仔细阅读', 'terms.desc1': '无内容托管: FreeIPTV Web 仅作为本地媒体播放器运行。我们不会在服务器上托管、分发任何视频或版权内容。', 'terms.desc2': '用户责任: 用户需对导入到此应用的任何 M3U 播放列表和内容承担全部责任。我们不对用户上传的内容负责。', 'terms.desc3': '本地数据: 我们绝不会收集您的个人数据。所有记录和列表均安全地保存在您的本地浏览器中。', 'terms.accept': '我已了解并同意',
    'player.streamError': '播放失败', 'player.streamErrorDesc': '该频道加载失败或存在地区限制。您可以尝试使用免费的 VPN 来解除网络屏蔽。', 'player.dismiss': '关闭'
  }
};

