export type TranslationKey = 
  | 'nav.home' | 'nav.world' | 'nav.favorites' | 'nav.myPlaylists' | 'nav.settings' | 'nav.about'
  | 'home.discover' | 'home.liveTv' | 'home.subtitle' | 'home.showingChannels' | 'home.search' | 'home.allChannels' | 'home.noChannels' | 'home.tryAdjusting'
  | 'world.title' | 'world.subtitle'
  | 'fav.title' | 'fav.subtitle' | 'fav.noFavs' | 'fav.clickHeart'
  | 'playlists.title' | 'playlists.subtitle' | 'playlists.dragDrop' | 'playlists.select' | 'playlists.noPlaylists' | 'playlists.uploadDesc' | 'playlists.channels'
  | 'settings.title' | 'settings.subtitle' | 'settings.theme' | 'settings.themeDesc' | 'settings.engine' | 'settings.engineDesc' | 'settings.autoplay' | 'settings.autoplayDesc' | 'settings.language' | 'settings.languageDesc'
  | 'settings.theme.dark' | 'settings.theme.light' | 'settings.theme.oled'
  | 'about.title' | 'about.subtitle' | 'about.version' | 'about.engine' | 'about.changelogs' | 'about.tryMobile' | 'about.free' | 'about.noAds' | 'about.openSource' | 'about.security' | 'about.securityDesc' | 'about.github' | 'about.website'
  | 'terms.title' | 'terms.subtitle' | 'terms.desc1' | 'terms.desc2' | 'terms.desc3' | 'terms.accept'
  | 'player.streamError' | 'player.streamErrorDesc' | 'player.dismiss';

type Dictionary = Record<TranslationKey, string>;

export const dictionaries: Record<string, Dictionary> = {
  en: {
    'nav.home': 'Home', 'nav.world': 'World', 'nav.favorites': 'Favorites', 'nav.myPlaylists': 'My Playlists', 'nav.settings': 'Settings', 'nav.about': 'About',
    'home.discover': 'Discover', 'home.liveTv': 'Live TV', 'home.subtitle': 'Stream your favorite channels with unparalleled speed and a stunning, distraction-free interface.', 'home.showingChannels': 'Showing {0} channels', 'home.search': 'Search channels, movies, sports...', 'home.allChannels': 'All Channels', 'home.noChannels': 'No channels found', 'home.tryAdjusting': 'Try adjusting your search or category filter.',
    'world.title': 'World Channels', 'world.subtitle': 'Explore 18,000+ international channels from around the globe.',
    'fav.title': 'Your Favorites', 'fav.subtitle': 'Curated collection of your most-watched channels.', 'fav.noFavs': 'No favorites yet', 'fav.clickHeart': 'Click the heart icon on any channel to save it here.',
    'playlists.title': 'My Playlists', 'playlists.subtitle': 'Upload and manage your own custom M3U playlists. Playlists are stored locally in your browser offline cache.', 'playlists.dragDrop': 'Drag & Drop your .m3u file here', 'playlists.select': 'Select Playlist', 'playlists.noPlaylists': 'No custom playlists yet', 'playlists.uploadDesc': 'Upload an M3U file above and it will securely appear here as a folder.', 'playlists.channels': 'Channels',
    'settings.title': 'Settings', 'settings.subtitle': 'Customize your viewing experience and application preferences.', 'settings.theme': 'App Theme', 'settings.themeDesc': 'Choose your preferred visual aesthetic.', 'settings.engine': 'Video Engine', 'settings.engineDesc': 'Select the core playback engine. If a stream fails, try switching engines.', 'settings.autoplay': 'Auto-play Channels', 'settings.autoplayDesc': 'Automatically start playing video when a channel is selected.', 'settings.language': 'Language', 'settings.languageDesc': 'Select your preferred display language.',
    'settings.theme.dark': 'Dark', 'settings.theme.light': 'Light', 'settings.theme.oled': 'OLED',
    'about.title': 'About', 'about.subtitle': 'FreeIPTV Web is a modern, lag-less live TV streaming application designed from the ground up for the ultimate viewing experience.', 'about.version': 'Version', 'about.engine': 'Engine', 'about.changelogs': 'Changelogs', 'about.tryMobile': 'Try Our Mobile App!', 'about.free': 'Free Forever', 'about.noAds': 'No Ads', 'about.openSource': 'Open Source', 'about.security': 'Security Notice:', 'about.securityDesc': 'Please only download the app from our official GitHub Releases to avoid malicious or unofficial APKs.', 'about.github': 'GitHub Releases', 'about.website': 'Official Website',
    'terms.title': 'Legal Disclaimer', 'terms.subtitle': 'Please read carefully before using FreeIPTV Web', 'terms.desc1': 'No Content Hosting: FreeIPTV Web is strictly a media player interface. We do not host, broadcast, or distribute any video streams, movies, or copyrighted content on our servers.', 'terms.desc2': 'User Responsibility: Any M3U playlists or stream links loaded into this application are the sole responsibility of the user. We are not responsible for the contents of user-uploaded playlists.', 'terms.desc3': 'Local Data: We do not collect or transmit your personal data or playlist contents to remote servers. All data is stored locally in your browser offline cache.', 'terms.accept': 'I Understand & Accept',
    'player.streamError': 'Stream Error', 'player.streamErrorDesc': 'This channel failed to load or is geo-blocked. Try using a free encrypted VPN to bypass ISP blocks.', 'player.dismiss': 'Dismiss'
  },
  bn: {
    'nav.home': 'হোম', 'nav.world': 'বিশ্ব', 'nav.favorites': 'প্রিয়', 'nav.myPlaylists': 'আমার প্লেলিস্ট', 'nav.settings': 'সেটিংস', 'nav.about': 'সম্পর্কে',
    'home.discover': 'আবিষ্কার করুন', 'home.liveTv': 'লাইভ টিভি', 'home.subtitle': 'অতুলনীয় গতি এবং একটি অত্যাশ্চর্য ইন্টারফেসের সাথে আপনার প্রিয় চ্যানেলগুলি স্ট্রিম করুন।', 'home.showingChannels': '{0} টি চ্যানেল দেখানো হচ্ছে', 'home.search': 'চ্যানেল, মুভি, খেলাধুলা খুঁজুন...', 'home.allChannels': 'সব চ্যানেল', 'home.noChannels': 'কোন চ্যানেল পাওয়া যায়নি', 'home.tryAdjusting': 'আপনার অনুসন্ধান বা বিভাগ ফিল্টার সামঞ্জস্য করার চেষ্টা করুন।',
    'world.title': 'বিশ্ব চ্যানেল', 'world.subtitle': 'বিশ্বজুড়ে ১৮,০০০+ আন্তর্জাতিক চ্যানেল অন্বেষণ করুন।',
    'fav.title': 'আপনার প্রিয়', 'fav.subtitle': 'আপনার সর্বাধিক দেখা চ্যানেলগুলির সংগ্রহ।', 'fav.noFavs': 'এখনও কোনো প্রিয় নেই', 'fav.clickHeart': 'যেকোনো চ্যানেলে হার্ট আইকনে ক্লিক করে এখানে সেভ করুন।',
    'playlists.title': 'আমার প্লেলিস্ট', 'playlists.subtitle': 'আপনার নিজস্ব কাস্টম M3U প্লেলিস্ট আপলোড এবং পরিচালনা করুন।', 'playlists.dragDrop': 'আপনার .m3u ফাইলটি এখানে টেনে আনুন', 'playlists.select': 'প্লেলিস্ট নির্বাচন করুন', 'playlists.noPlaylists': 'এখনও কোনো কাস্টম প্লেলিস্ট নেই', 'playlists.uploadDesc': 'উপরে একটি M3U ফাইল আপলোড করুন এবং এটি একটি ফোল্ডার হিসাবে এখানে উপস্থিত হবে।', 'playlists.channels': 'চ্যানেল',
    'settings.title': 'সেটিংস', 'settings.subtitle': 'আপনার দেখার অভিজ্ঞতা কাস্টমাইজ করুন।', 'settings.theme': 'অ্যাপ থিম', 'settings.themeDesc': 'আপনার পছন্দের ভিজ্যুয়াল নান্দনিক চয়ন করুন।', 'settings.engine': 'ভিডিও ইঞ্জিন', 'settings.engineDesc': 'কোর প্লেব্যাক ইঞ্জিন নির্বাচন করুন।', 'settings.autoplay': 'স্বয়ংক্রিয়-প্লে চ্যানেল', 'settings.autoplayDesc': 'চ্যানেল নির্বাচন করার সময় স্বয়ংক্রিয়ভাবে ভিডিও প্লে শুরু করুন।', 'settings.language': 'ভাষা', 'settings.languageDesc': 'আপনার পছন্দের ভাষা নির্বাচন করুন।',
    'settings.theme.dark': 'অন্ধকার', 'settings.theme.light': 'আলো', 'settings.theme.oled': 'ওএলইডি (OLED)',
    'about.title': 'সম্পর্কে', 'about.subtitle': 'ফ্রিআইপিটিভি ওয়েব একটি আধুনিক, ল্যাগ-লেস লাইভ টিভি স্ট্রিমিং অ্যাপ্লিকেশন।', 'about.version': 'সংস্করণ', 'about.engine': 'ইঞ্জিন', 'about.changelogs': 'পরিবর্তন লগ', 'about.tryMobile': 'আমাদের মোবাইল অ্যাপ চেষ্টা করুন!', 'about.free': 'চিরতরে বিনামূল্যে', 'about.noAds': 'কোনো বিজ্ঞাপন নেই', 'about.openSource': 'ওপেন সোর্স', 'about.security': 'নিরাপত্তা বিজ্ঞপ্তি:', 'about.securityDesc': 'ক্ষতিকারক এপিকে এড়াতে দয়া করে আমাদের অফিসিয়াল গিটহাব থেকে অ্যাপটি ডাউনলোড করুন।', 'about.github': 'গিটহাব রিলিজ', 'about.website': 'অফিসিয়াল ওয়েবসাইট',
    'terms.title': 'আইনী দাবিত্যাগ', 'terms.subtitle': 'ব্যবহার করার আগে দয়া করে সাবধানে পড়ুন', 'terms.desc1': 'কোন সামগ্রী হোস্টিং নেই: ফ্রিআইপিটিভি ওয়েব কঠোরভাবে একটি মিডিয়া প্লেয়ার। আমরা কোনো ভিডিও স্ট্রিম হোস্ট করি না।', 'terms.desc2': 'ব্যবহারকারীর দায়িত্ব: এই অ্যাপ্লিকেশনে লোড করা যেকোনো M3U প্লেলিস্ট ব্যবহারকারীর একমাত্র দায়িত্ব।', 'terms.desc3': 'স্থানীয় ডেটা: আমরা আপনার ব্যক্তিগত ডেটা সংগ্রহ করি না। সমস্ত ডেটা আপনার ব্রাউজারে স্থানীয়ভাবে সংরক্ষণ করা হয়।', 'terms.accept': 'আমি বুঝতে পেরেছি এবং গ্রহণ করছি',
    'player.streamError': 'স্ট্রিম ত্রুটি', 'player.streamErrorDesc': 'এই চ্যানেলটি লোড হতে ব্যর্থ হয়েছে বা জিও-ব্লক করা হয়েছে।', 'player.dismiss': 'বাতিল করুন'
  },
  es: {
    'nav.home': 'Inicio', 'nav.world': 'Mundo', 'nav.favorites': 'Favoritos', 'nav.myPlaylists': 'Mis Listas', 'nav.settings': 'Ajustes', 'nav.about': 'Acerca de',
    'home.discover': 'Descubrir', 'home.liveTv': 'TV en Vivo', 'home.subtitle': 'Transmite tus canales favoritos con una velocidad incomparable y una interfaz impresionante.', 'home.showingChannels': 'Mostrando {0} canales', 'home.search': 'Buscar canales, películas, deportes...', 'home.allChannels': 'Todos los Canales', 'home.noChannels': 'No se encontraron canales', 'home.tryAdjusting': 'Intenta ajustar tu búsqueda.',
    'world.title': 'Canales del Mundo', 'world.subtitle': 'Explora más de 18,000 canales internacionales.',
    'fav.title': 'Tus Favoritos', 'fav.subtitle': 'Colección seleccionada de tus canales más vistos.', 'fav.noFavs': 'Aún no hay favoritos', 'fav.clickHeart': 'Haz clic en el icono del corazón en cualquier canal para guardarlo aquí.',
    'playlists.title': 'Mis Listas de Reproducción', 'playlists.subtitle': 'Sube y gestiona tus propias listas M3U personalizadas.', 'playlists.dragDrop': 'Arrastra y suelta tu archivo .m3u aquí', 'playlists.select': 'Seleccionar Lista', 'playlists.noPlaylists': 'Aún no hay listas personalizadas', 'playlists.uploadDesc': 'Sube un archivo M3U arriba y aparecerá aquí.', 'playlists.channels': 'Canales',
    'settings.title': 'Ajustes', 'settings.subtitle': 'Personaliza tu experiencia de visualización.', 'settings.theme': 'Tema de la App', 'settings.themeDesc': 'Elige tu estética visual preferida.', 'settings.engine': 'Motor de Video', 'settings.engineDesc': 'Selecciona el motor de reproducción principal.', 'settings.autoplay': 'Reproducción Automática', 'settings.autoplayDesc': 'Inicia la reproducción del video automáticamente.', 'settings.language': 'Idioma', 'settings.languageDesc': 'Selecciona tu idioma preferido.',
    'settings.theme.dark': 'Oscuro', 'settings.theme.light': 'Claro', 'settings.theme.oled': 'OLED',
    'about.title': 'Acerca de', 'about.subtitle': 'FreeIPTV Web es una aplicación moderna de transmisión de TV en vivo sin demoras.', 'about.version': 'Versión', 'about.engine': 'Motor', 'about.changelogs': 'Registros de cambios', 'about.tryMobile': '¡Prueba Nuestra App Móvil!', 'about.free': 'Gratis Siempre', 'about.noAds': 'Sin Anuncios', 'about.openSource': 'Código Abierto', 'about.security': 'Aviso de Seguridad:', 'about.securityDesc': 'Por favor, descarga la aplicación solo desde nuestro GitHub oficial para evitar APKs maliciosos.', 'about.github': 'Lanzamientos en GitHub', 'about.website': 'Sitio Web Oficial',
    'terms.title': 'Aviso Legal', 'terms.subtitle': 'Lee detenidamente antes de usar FreeIPTV Web', 'terms.desc1': 'Sin alojamiento de contenido: FreeIPTV Web es estrictamente un reproductor multimedia. No alojamos ninguna transmisión de video.', 'terms.desc2': 'Responsabilidad del usuario: Cualquier lista M3U cargada en esta aplicación es responsabilidad exclusiva del usuario.', 'terms.desc3': 'Datos Locales: No recopilamos tus datos personales. Todos los datos se almacenan localmente en tu navegador.', 'terms.accept': 'Entiendo y Acepto',
    'player.streamError': 'Error de Transmisión', 'player.streamErrorDesc': 'Este canal no pudo cargarse o está bloqueado geográficamente.', 'player.dismiss': 'Descartar'
  },
  ru: {
    'nav.home': 'Главная', 'nav.world': 'Мир', 'nav.favorites': 'Избранное', 'nav.myPlaylists': 'Мои Плейлисты', 'nav.settings': 'Настройки', 'nav.about': 'О нас',
    'home.discover': 'Откройте', 'home.liveTv': 'Прямой эфир', 'home.subtitle': 'Смотрите любимые каналы с невероятной скоростью и потрясающим интерфейсом.', 'home.showingChannels': 'Показано {0} каналов', 'home.search': 'Поиск каналов, фильмов, спорта...', 'home.allChannels': 'Все каналы', 'home.noChannels': 'Каналы не найдены', 'home.tryAdjusting': 'Попробуйте изменить параметры поиска.',
    'world.title': 'Мировые каналы', 'world.subtitle': 'Исследуйте более 18 000 международных каналов.',
    'fav.title': 'Ваше избранное', 'fav.subtitle': 'Тщательно отобранная коллекция ваших каналов.', 'fav.noFavs': 'Пока нет избранного', 'fav.clickHeart': 'Нажмите на значок сердца, чтобы сохранить канал.',
    'playlists.title': 'Мои Плейлисты', 'playlists.subtitle': 'Загружайте и управляйте своими M3U плейлистами.', 'playlists.dragDrop': 'Перетащите ваш файл .m3u сюда', 'playlists.select': 'Выбрать плейлист', 'playlists.noPlaylists': 'Нет пользовательских плейлистов', 'playlists.uploadDesc': 'Загрузите файл M3U, и он появится здесь.', 'playlists.channels': 'Каналы',
    'settings.title': 'Настройки', 'settings.subtitle': 'Настройте просмотр под себя.', 'settings.theme': 'Тема приложения', 'settings.themeDesc': 'Выберите предпочитаемый визуальный стиль.', 'settings.engine': 'Видео движок', 'settings.engineDesc': 'Выберите основной движок воспроизведения.', 'settings.autoplay': 'Автовоспроизведение', 'settings.autoplayDesc': 'Автоматически запускать видео при выборе канала.', 'settings.language': 'Язык', 'settings.languageDesc': 'Выберите предпочитаемый язык.',
    'settings.theme.dark': 'Темная', 'settings.theme.light': 'Светлая', 'settings.theme.oled': 'OLED',
    'about.title': 'О нас', 'about.subtitle': 'FreeIPTV Web — это современное приложение для просмотра ТВ в прямом эфире.', 'about.version': 'Версия', 'about.engine': 'Движок', 'about.changelogs': 'Список изменений', 'about.tryMobile': 'Попробуйте наше мобильное приложение!', 'about.free': 'Навсегда бесплатно', 'about.noAds': 'Без рекламы', 'about.openSource': 'Открытый исходный код', 'about.security': 'Уведомление о безопасности:', 'about.securityDesc': 'Загружайте приложение только с официального GitHub.', 'about.github': 'Релизы GitHub', 'about.website': 'Официальный сайт',
    'terms.title': 'Отказ от ответственности', 'terms.subtitle': 'Пожалуйста, внимательно прочитайте перед использованием', 'terms.desc1': 'Нет хостинга: FreeIPTV Web — это только медиаплеер. Мы не размещаем видеопотоки.', 'terms.desc2': 'Ответственность пользователя: Любые загруженные M3U плейлисты являются ответственностью пользователя.', 'terms.desc3': 'Локальные данные: Мы не собираем личные данные. Все данные хранятся локально.', 'terms.accept': 'Я понимаю и принимаю',
    'player.streamError': 'Ошибка потока', 'player.streamErrorDesc': 'Не удалось загрузить этот канал или он заблокирован.', 'player.dismiss': 'Закрыть'
  },
  ar: {
    'nav.home': 'الرئيسية', 'nav.world': 'العالم', 'nav.favorites': 'المفضلة', 'nav.myPlaylists': 'قوائمي', 'nav.settings': 'الإعدادات', 'nav.about': 'حول',
    'home.discover': 'اكتشف', 'home.liveTv': 'البث المباشر', 'home.subtitle': 'قم ببث قنواتك المفضلة بسرعة لا مثيل لها وواجهة مذهلة.', 'home.showingChannels': 'عرض {0} قنوات', 'home.search': 'البحث عن القنوات، الأفلام، الرياضة...', 'home.allChannels': 'جميع القنوات', 'home.noChannels': 'لم يتم العثور على قنوات', 'home.tryAdjusting': 'حاول تعديل البحث أو مرشح الفئة.',
    'world.title': 'قنوات العالم', 'world.subtitle': 'استكشف أكثر من 18000 قناة دولية.',
    'fav.title': 'مفضلاتك', 'fav.subtitle': 'مجموعة من القنوات الأكثر مشاهدة.', 'fav.noFavs': 'لا توجد مفضلات بعد', 'fav.clickHeart': 'انقر على أيقونة القلب في أي قناة لحفظها هنا.',
    'playlists.title': 'قوائم التشغيل الخاصة بي', 'playlists.subtitle': 'قم بتحميل وإدارة قوائم تشغيل M3U الخاصة بك.', 'playlists.dragDrop': 'قم بسحب وإسقاط ملف .m3u الخاص بك هنا', 'playlists.select': 'اختر قائمة التشغيل', 'playlists.noPlaylists': 'لا توجد قوائم تشغيل مخصصة بعد', 'playlists.uploadDesc': 'قم بتحميل ملف M3U أعلاه وسيظهر هنا.', 'playlists.channels': 'قنوات',
    'settings.title': 'الإعدادات', 'settings.subtitle': 'قم بتخصيص تجربة المشاهدة والتفضيلات الخاصة بك.', 'settings.theme': 'سمة التطبيق', 'settings.themeDesc': 'اختر المظهر المرئي المفضل لديك.', 'settings.engine': 'محرك الفيديو', 'settings.engineDesc': 'حدد محرك التشغيل الأساسي.', 'settings.autoplay': 'التشغيل التلقائي', 'settings.autoplayDesc': 'بدء تشغيل الفيديو تلقائيا عند اختيار قناة.', 'settings.language': 'اللغة', 'settings.languageDesc': 'حدد لغة العرض المفضلة لديك.',
    'settings.theme.dark': 'داكن', 'settings.theme.light': 'فاتح', 'settings.theme.oled': 'OLED',
    'about.title': 'حول', 'about.subtitle': 'FreeIPTV Web هو تطبيق حديث لبث التلفزيون المباشر.', 'about.version': 'الإصدار', 'about.engine': 'المحرك', 'about.changelogs': 'سجلات التغيير', 'about.tryMobile': 'جرب تطبيقنا المحمول!', 'about.free': 'مجاني للأبد', 'about.noAds': 'بدون إعلانات', 'about.openSource': 'مفتوح المصدر', 'about.security': 'إشعار أمني:', 'about.securityDesc': 'يرجى تنزيل التطبيق فقط من إصدارات GitHub الرسمية الخاصة بنا.', 'about.github': 'إصدارات GitHub', 'about.website': 'الموقع الرسمي',
    'terms.title': 'إخلاء المسؤولية القانونية', 'terms.subtitle': 'يرجى القراءة بعناية قبل الاستخدام', 'terms.desc1': 'لا يوجد استضافة للمحتوى: هذا التطبيق هو مجرد مشغل وسائط. نحن لا نستضيف أي قنوات.', 'terms.desc2': 'مسؤولية المستخدم: أي قوائم M3U يتم تحميلها هي مسؤولية المستخدم وحده.', 'terms.desc3': 'البيانات المحلية: نحن لا نجمع بياناتك الشخصية. يتم تخزين جميع البيانات محليًا.', 'terms.accept': 'أنا أفهم وأقبل',
    'player.streamError': 'خطأ في البث', 'player.streamErrorDesc': 'فشل تحميل هذه القناة أو تم حظرها جغرافيًا.', 'player.dismiss': 'تجاهل'
  },
  hi: {
    'nav.home': 'होम', 'nav.world': 'दुनिया', 'nav.favorites': 'पसंदीदा', 'nav.myPlaylists': 'मेरी प्लेलिस्ट', 'nav.settings': 'सेटिंग्स', 'nav.about': 'के बारे में',
    'home.discover': 'खोजें', 'home.liveTv': 'लाइव टीवी', 'home.subtitle': 'बेजोड़ गति और शानदार इंटरफ़ेस के साथ अपने पसंदीदा चैनल स्ट्रीम करें।', 'home.showingChannels': '{0} चैनल दिखा रहा है', 'home.search': 'चैनल, फिल्में, खेल खोजें...', 'home.allChannels': 'सभी चैनल', 'home.noChannels': 'कोई चैनल नहीं मिला', 'home.tryAdjusting': 'अपनी खोज या श्रेणी फ़िल्टर समायोजित करने का प्रयास करें।',
    'world.title': 'विश्व चैनल', 'world.subtitle': 'दुनिया भर से 18,000+ अंतर्राष्ट्रीय चैनलों का अन्वेषण करें।',
    'fav.title': 'आपकी पसंदीदा', 'fav.subtitle': 'आपके सबसे ज्यादा देखे गए चैनलों का संग्रह।', 'fav.noFavs': 'अभी तक कोई पसंदीदा नहीं', 'fav.clickHeart': 'किसी भी चैनल को यहाँ सहेजने के लिए हार्ट आइकन पर क्लिक करें।',
    'playlists.title': 'मेरी प्लेलिस्ट', 'playlists.subtitle': 'अपनी खुद की कस्टम M3U प्लेलिस्ट अपलोड और प्रबंधित करें।', 'playlists.dragDrop': 'अपनी .m3u फ़ाइल यहाँ खींचें और छोड़ें', 'playlists.select': 'प्लेलिस्ट चुनें', 'playlists.noPlaylists': 'अभी तक कोई कस्टम प्लेलिस्ट नहीं', 'playlists.uploadDesc': 'ऊपर एक M3U फ़ाइल अपलोड करें और यह यहाँ दिखाई देगी।', 'playlists.channels': 'चैनल',
    'settings.title': 'सेटिंग्स', 'settings.subtitle': 'अपने देखने के अनुभव और एप्लिकेशन प्राथमिकताओं को अनुकूलित करें।', 'settings.theme': 'ऐप थीम', 'settings.themeDesc': 'अपना पसंदीदा विज़ुअल चुनें।', 'settings.engine': 'वीडियो इंजन', 'settings.engineDesc': 'मुख्य प्लेबैक इंजन चुनें।', 'settings.autoplay': 'ऑटो-प्ले', 'settings.autoplayDesc': 'चैनल का चयन करते ही स्वचालित रूप से वीडियो चलाना शुरू करें।', 'settings.language': 'भाषा', 'settings.languageDesc': 'अपनी पसंदीदा प्रदर्शन भाषा चुनें।',
    'settings.theme.dark': 'डार्क', 'settings.theme.light': 'लाइट', 'settings.theme.oled': 'OLED',
    'about.title': 'के बारे में', 'about.subtitle': 'FreeIPTV Web एक आधुनिक लाइव टीवी स्ट्रीमिंग एप्लिकेशन है।', 'about.version': 'संस्करण', 'about.engine': 'इंजन', 'about.changelogs': 'चेंजलॉग', 'about.tryMobile': 'हमारा मोबाइल ऐप आज़माएं!', 'about.free': 'हमेशा के लिए मुफ़्त', 'about.noAds': 'कोई विज्ञापन नहीं', 'about.openSource': 'ओपन सोर्स', 'about.security': 'सुरक्षा नोटिस:', 'about.securityDesc': 'कृपया दुर्भावनापूर्ण ऐप्स से बचने के लिए केवल हमारे आधिकारिक GitHub से ऐप डाउनलोड करें।', 'about.github': 'GitHub रिलीज़', 'about.website': 'आधिकारिक वेबसाइट',
    'terms.title': 'कानूनी अस्वीकरण', 'terms.subtitle': 'उपयोग करने से पहले कृपया ध्यान से पढ़ें', 'terms.desc1': 'कोई सामग्री होस्टिंग नहीं: यह ऐप केवल एक मीडिया प्लेयर है। हम किसी भी वीडियो को होस्ट नहीं करते हैं।', 'terms.desc2': 'उपयोगकर्ता की जिम्मेदारी: इस एप्लिकेशन में लोड की गई कोई भी M3U प्लेलिस्ट उपयोगकर्ता की एकमात्र जिम्मेदारी है।', 'terms.desc3': 'स्थानीय डेटा: हम आपका व्यक्तिगत डेटा एकत्र नहीं करते हैं। सभी डेटा आपके ब्राउज़र में स्थानीय रूप से संग्रहीत किया जाता है।', 'terms.accept': 'मैं समझता हूँ और स्वीकार करता हूँ',
    'player.streamError': 'स्ट्रीम त्रुटि', 'player.streamErrorDesc': 'यह चैनल लोड होने में विफल रहा या जियो-ब्लॉक किया गया है।', 'player.dismiss': 'खारिज करें'
  },
  ja: {
    'nav.home': 'ホーム', 'nav.world': '世界', 'nav.favorites': 'お気に入り', 'nav.myPlaylists': 'マイプレイリスト', 'nav.settings': '設定', 'nav.about': '情報',
    'home.discover': '発見', 'home.liveTv': 'ライブTV', 'home.subtitle': '比類のない速度と見事なインターフェイスでお気に入りのチャンネルをストリーミングします。', 'home.showingChannels': '{0} チャンネルを表示中', 'home.search': 'チャンネル、映画、スポーツを検索...', 'home.allChannels': 'すべてのチャンネル', 'home.noChannels': 'チャンネルが見つかりません', 'home.tryAdjusting': '検索またはカテゴリフィルターを調整してみてください。',
    'world.title': '世界のチャンネル', 'world.subtitle': '世界中の18,000以上の国際チャンネルを探索。',
    'fav.title': 'あなたのお気に入り', 'fav.subtitle': '最も視聴されたチャンネルのコレクション。', 'fav.noFavs': 'お気に入りはまだありません', 'fav.clickHeart': 'ハートアイコンをクリックしてチャンネルを保存します。',
    'playlists.title': 'マイプレイリスト', 'playlists.subtitle': 'カスタムM3Uプレイリストをアップロードして管理します。', 'playlists.dragDrop': '.m3uファイルをここにドラッグ＆ドロップ', 'playlists.select': 'プレイリストを選択', 'playlists.noPlaylists': 'カスタムプレイリストはまだありません', 'playlists.uploadDesc': 'M3Uファイルをアップロードすると、ここに表示されます。', 'playlists.channels': 'チャンネル',
    'settings.title': '設定', 'settings.subtitle': '表示エクスペリエンスとアプリケーション設定をカスタマイズします。', 'settings.theme': 'アプリのテーマ', 'settings.themeDesc': '好みの視覚的な美しさを選択してください。', 'settings.engine': 'ビデオエンジン', 'settings.engineDesc': 'コア再生エンジンを選択します。', 'settings.autoplay': '自動再生', 'settings.autoplayDesc': 'チャンネルを選択すると自動的にビデオの再生を開始します。', 'settings.language': '言語', 'settings.languageDesc': '好みの表示言語を選択してください。',
    'settings.theme.dark': 'ダーク', 'settings.theme.light': 'ライト', 'settings.theme.oled': 'OLED',
    'about.title': '情報', 'about.subtitle': 'FreeIPTV Webは、最新のラグのないライブTVストリーミングアプリケーションです。', 'about.version': 'バージョン', 'about.engine': 'エンジン', 'about.changelogs': '変更履歴', 'about.tryMobile': 'モバイルアプリをお試しください！', 'about.free': '永久無料', 'about.noAds': '広告なし', 'about.openSource': 'オープンソース', 'about.security': 'セキュリティ通知:', 'about.securityDesc': '悪意のあるアプリを避けるために、公式のGitHubからのみアプリをダウンロードしてください。', 'about.github': 'GitHubリリース', 'about.website': '公式サイト',
    'terms.title': '免責事項', 'terms.subtitle': '使用する前に注意深くお読みください', 'terms.desc1': 'コンテンツのホスティングなし: FreeIPTV Webは厳密にはメディアプレーヤーです。ビデオストリームはホストしていません。', 'terms.desc2': 'ユーザーの責任: アップロードされたM3Uプレイリストは、ユーザーの単独の責任です。', 'terms.desc3': 'ローカルデータ: 個人データは収集しません。すべてのデータはローカルに保存されます。', 'terms.accept': '理解して同意する',
    'player.streamError': 'ストリームエラー', 'player.streamErrorDesc': 'このチャンネルの読み込みに失敗したか、ジオブロックされています。', 'player.dismiss': '閉じる'
  },
  zh: {
    'nav.home': '首页', 'nav.world': '世界', 'nav.favorites': '收藏', 'nav.myPlaylists': '我的播放列表', 'nav.settings': '设置', 'nav.about': '关于',
    'home.discover': '发现', 'home.liveTv': '直播电视', 'home.subtitle': '以无与伦比的速度和令人惊叹的界面流式传输您喜爱的频道。', 'home.showingChannels': '显示 {0} 个频道', 'home.search': '搜索频道、电影、体育...', 'home.allChannels': '所有频道', 'home.noChannels': '未找到频道', 'home.tryAdjusting': '尝试调整您的搜索或类别过滤器。',
    'world.title': '世界频道', 'world.subtitle': '探索来自全球的18,000多个国际频道。',
    'fav.title': '您的收藏', 'fav.subtitle': '您最常观看的频道的精选集合。', 'fav.noFavs': '暂无收藏', 'fav.clickHeart': '点击频道上的心形图标将其保存到这里。',
    'playlists.title': '我的播放列表', 'playlists.subtitle': '上传并管理您自己的自定义M3U播放列表。', 'playlists.dragDrop': '将您的.m3u文件拖放到此处', 'playlists.select': '选择播放列表', 'playlists.noPlaylists': '暂无自定义播放列表', 'playlists.uploadDesc': '上传M3U文件，它将显示在此处。', 'playlists.channels': '频道',
    'settings.title': '设置', 'settings.subtitle': '自定义您的观看体验和应用程序首选项。', 'settings.theme': '应用主题', 'settings.themeDesc': '选择您喜欢的视觉美感。', 'settings.engine': '视频引擎', 'settings.engineDesc': '选择核心播放引擎。', 'settings.autoplay': '自动播放', 'settings.autoplayDesc': '选择频道时自动开始播放视频。', 'settings.language': '语言', 'settings.languageDesc': '选择您首选的显示语言。',
    'settings.theme.dark': '深色', 'settings.theme.light': '浅色', 'settings.theme.oled': 'OLED',
    'about.title': '关于', 'about.subtitle': 'FreeIPTV Web 是一款现代、无延迟的直播电视流媒体应用程序。', 'about.version': '版本', 'about.engine': '引擎', 'about.changelogs': '更新日志', 'about.tryMobile': '尝试我们的移动应用！', 'about.free': '永久免费', 'about.noAds': '无广告', 'about.openSource': '开源', 'about.security': '安全通知:', 'about.securityDesc': '请仅从我们官方的GitHub下载应用程序，以避免恶意应用。', 'about.github': 'GitHub 发布', 'about.website': '官方网站',
    'terms.title': '免责声明', 'terms.subtitle': '使用前请仔细阅读', 'terms.desc1': '无内容托管: FreeIPTV Web 严格来说只是一个媒体播放器。我们不托管任何视频流。', 'terms.desc2': '用户责任: 上传的任何M3U播放列表均由用户自行负责。', 'terms.desc3': '本地数据: 我们不收集您的个人数据。所有数据均本地存储。', 'terms.accept': '我理解并接受',
    'player.streamError': '流错误', 'player.streamErrorDesc': '此频道加载失败或被地理封锁。', 'player.dismiss': '关闭'
  }
};
